### ISSUE TITLE
How to generate auth bearer token

### ISSUE THREAD

**Issue by amitabhajana** [MerginMaps/server#133] opened 2023-11-28 07:41 UTC
Hi,

I'm new to using mergin maps. Kindly guide me on how to generate auth bearer token of mergin maps endpoint.

**Comment by wonder-sk** [comment] 2023-11-28 08:09
Duplicate of https://github.com/MerginMaps/python-api-client/issues/194

**Closed by wonder-sk** 2023-11-28 08:09 UTC
